name: BMSwiftApp
options:
  bundleIdPrefix: com.bbmsft
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
  defaultConfig: Debug
  platform: iOS
  createIntermediateGroups: true
  generateEmptyDirectories: true
packages:
  BMSwift:
    path: ..
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.2
targets:
  BMSwiftApp:
    type: application
    platform: iOS
    sources:
      - path: BMSwiftApp
        excludes:
          - "*.md"
          - "*.yml"
    dependencies:
      - package: BMSwift
        product: BMSwift
      - package: KeychainAccess
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework
      - sdk: Foundation.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bbmsft.BMSwiftApp
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""  # You'll need to set this
        INFOPLIST_FILE: BMSwiftApp/Info.plist
        PRODUCT_NAME: BMSwiftApp
        TARGETED_DEVICE_FAMILY: 1,2
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        ENABLE_PREVIEWS: YES
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

